version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: echo build step
      - run: npm test

  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo test step
      - run: npm install
      - run: npm test

  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo deploy step

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      # - hold:
      #     type: approval
      #     requires:
      #       - test
      - deploy:
          requires:
            # - hold
              - test
          filters:
            branches:
              only:
                - master